# We're only here to build a DLL around the .LIB files that 
# Data Translation provides, since Python's ctypes library
# can't work with .LIB. So, here we have a stupid little wrapper that 
# simply exports the parts of the .LIB that we need to be able to 
# work with.

DTROOT = "C:\Program Files (x86)\Data Translation\Win32\SDK"
DTINCLUDE = /I$(DTROOT)\Include
DTLIBS = /LIBPATH:$(DTROOT)\Lib64 oldaapi64.lib OLMEM64.lib Graph64.lib

CXXFLAGS = /MD /EHsc /DWIN32 /D_AMD64_ /D_WINDOWS /DNOPCH /O2 $(DTINCLUDE)

DTOBJS = dt_wrapper.obj
DTTARGET = dt_wrapper.dll

all: $(DTTARGET)

$(DTTARGET): $(DTOBJS)
    link /dll /DEBUG /NOLOGO /out:$@ /SUBSYSTEM:WINDOWS $(DTOBJS) $(DTLIBS)

clean:
    del *lib *pdb *obj *exp *dll
